name: Behave Checkin Validation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  behave-checkin-validation:
    runs-on: ubuntu-latest
    
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      PYTHONIOENCODING: utf-8
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          cd server
          pip install -r requirements.txt
      
      - name: Start API server (background)
        run: |
          cd server
          python -m uvicorn src.main:app --host 0.0.0.0 --port 8000 &
          sleep 10  # Give server time to start
        
      - name: Run Behave checkin tests
        run: |
          cd server
          behave --tags=checkin
        
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: behave-test-results
          path: server/reports/